# Use a specific Python version (adjust if needed)
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the entire current directory contents to the container's working directory
COPY . .

# Run the main script
CMD [ "python", "main.py" ]
