FROM node:20.8.0-alpine3.18

LABEL name="Node Application" \   
     maintainer="Daoud Hussain <dev.daoudhussain@gmail.com>" \
     summary="A Node Sample application"

# Create app directory
WORKDIR /app

EXPOSE 8000

COPY index.js ./

CMD [ "node", "index.js" ]